In [1]:
import pandas as pd
import numpy as np
import datetime as dt

# Анализ датасетов, восстановление наименований полей

In [2]:
hist_addr = pd.read_csv('socgaz_hist_ADDR.csv', sep = ';', header = None)
hist_addr.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,398286971,bab755ea-37b7-11ec-8980-0050569c399d,94f6e7d8-de4f-11eb-8931-0050569c399d,"д.Боровково, микрорайон Восточный, д.16",50:16:0203020:503,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:151,"Российская Федерация, Московская область, Бого...",2021-11-15 00:00:00.000,NaN,2021-11-15 00:00:00.000,NaN,2022-02-13
1,398286971,bab755eb-37b7-11ec-8980-0050569c399d,f11a3a93-de49-11eb-8931-0050569c399d,"д.Боровково, микрорайон Восточный, д.17",50:16:0203020:183,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:150,"Российская Федерация, Московская область, Бого...",2021-11-15 00:00:00.000,NaN,2021-12-07 00:00:00.000,NaN,2022-02-13
2,398286971,bab755ec-37b7-11ec-8980-0050569c399d,98815216-c545-11eb-8906-0050569c399d,"д.Боровково, микрорайон Восточный, д.19",50:16:0203020:185,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:93,"Московская область, Ногинский район, сельское ...",2021-11-15 00:00:00.000,NaN,NaN,NaN,2022-02-13

In [3]:
# На основе анализа таблицы ADDR в отчете PowerBI определяем названия полей
columnnames = {
    0: 'SETTL_FID',
    1: 'ADDR_GUID',
    2: 'REQ_GUID',
    3: 'Адрес',
    4: 'КадастровыйНомерОбъектаКС',
    5: 'АдресОбъектаКС',
    6: 'ТипОбъектаКС',
    7: 'КадастровыйНомерЗУ',
    8: 'АдресЗУ',
    9: 'ДатаСтроительстваГазопроводВвода',
    10: 'ДатаВыполненияПИР_КЧ',
    11: 'ДатаВыполненияСМР_КЧ',
    12: 'ДатаПускаГаза'       
}

In [4]:
hist_addr = hist_addr.rename(columns=columnnames)
hist_addr.head(3)

,SETTL_FID,ADDR_GUID,REQ_GUID,Адрес,КадастровыйНомерОбъектаКС,АдресОбъектаКС,ТипОбъектаКС,КадастровыйНомерЗУ,АдресЗУ,ДатаСтроительстваГазопроводВвода,ДатаВыполненияПИР_КЧ,ДатаВыполненияСМР_КЧ,ДатаПускаГаза,13
0,398286971,bab755ea-37b7-11ec-8980-0050569c399d,94f6e7d8-de4f-11eb-8931-0050569c399d,"д.Боровково, микрорайон Восточный, д.16",50:16:0203020:503,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:151,"Российская Федерация, Московская область, Бого...",2021-11-15 00:00:00.000,NaN,2021-11-15 00:00:00.000,NaN,2022-02-13
1,398286971,bab755eb-37b7-11ec-8980-0050569c399d,f11a3a93-de49-11eb-8931-0050569c399d,"д.Боровково, микрорайон Восточный, д.17",50:16:0203020:183,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:150,"Российская Федерация, Московская область, Бого...",2021-11-15 00:00:00.000,NaN,2021-12-07 00:00:00.000,NaN,2022-02-13
2,398286971,bab755ec-37b7-11ec-8980-0050569c399d,98815216-c545-11eb-8906-0050569c399d,"д.Боровково, микрорайон Восточный, д.19",50:16:0203020:185,"Российская Федерация, Московская область, Бого...",Жилое,50:16:0203020:93,"Московская область, Ногинский район, сельское ...",2021-11-15 00:00:00.000,NaN,NaN,NaN,2022-02-13

In [5]:
hist_addr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465231 entries, 0 to 465230
Data columns (total 14 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   SETTL_FID                         465231 non-null  int64
 1   ADDR_GUID                         465231 non-null  object
 2   REQ_GUID                          465231 non-null  object
 3   Адрес                             458293 non-null  object
 4   КадастровыйНомерОбъектаКС         182717 non-null  object
 5   АдресОбъектаКС                    224010 non-null  object
 6   ТипОбъектаКС                      200515 non-null  object
 7   КадастровыйНомерЗУ                392114 non-null  object
 8   АдресЗУ                           353262 non-null  object
 9   ДатаСтроительстваГазопроводВвода  47662 non-null   object
 10  ДатаВыполненияПИР_КЧ              5279 non-null    object
 11  ДатаВыполненияСМР_КЧ              5523 non-null    object
 12  ДатаПускаГаза                     8110 non-null    object
 13  13                                465231 non-null  object
dtypes: int64(1), object(13)
memory usage: 49.7+ MB

In [6]:
hist_addr['REQ_GUID'].nunique()

42195

In [7]:
hist_agr = pd.read_csv('socgaz_hist_AGR.csv', sep = ';', header = None)
hist_agr.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,00dd53ee-7ec5-11ec-8981-0050569c399d,Действует,08/-Д13358-21,2021-10-08 00:00:00.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,00dd53ef-7ec5-11ec-8981-0050569c399d,2022-02-13
1,00dd53f2-7ec5-11ec-8981-0050569c399d,Действует,08/-Д13359-21,2021-10-08 00:00:00.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,00dd53f3-7ec5-11ec-8981-0050569c399d,2022-02-13

In [8]:
hist_agr.loc[(hist_agr[4].notna())&(hist_agr[14].notna())].head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
14,00e7e8fe-155e-11ec-897f-0050569c399d,#ПустоеЗначение#,05/11 881-Д10932-2021-КОМ,2021-09-14 00:00:00.000,2021-09-14 00:00:00.000,2022-01-14 00:00:00.000,NaN,115662.87,7300.0,76093.19,20924.68,5945.0,5400.0,0.0,90985.75,75821.45,2021-09-24 17:22:47.000,3c5d6a25-148c-11ec-897e-0050569c399d,2022-02-13
17,00ea8952-0bbe-11ec-8973-0050569c399d,#ПустоеЗначение#,06/12037-Д11902-2021-КОМ,2021-08-22 00:00:00.000,2021-08-22 00:00:00.000,2022-08-22 00:00:00.000,NaN,148816.31,7300.0,101919.77,26196.54,4700.0,8700.0,0.0,99210.88,82675.68,2021-09-20 00:00:00.000,8443fb99-0b6e-11ec-8972-0050569c399d,2022-02-13

In [9]:
# На основе анализа таблицы AGR по записи 00e7e8fe-155e-11ec-897f-0050569c399d в отчете PowerBI определяем названия полей
columnnames = {
    0: 'AGR_GUID',
    1: 'Статус',
    2: 'Номер',
    3: 'Дата',
    4: 'ДатаНачалаДействия',
    5: 'ДатаОкончанияДействия',
    6: 'ДатаПодписанияДоговораЗаявителем',
    7: 'СтоимостьДоговора',
    8: 'СтоимостьКЧ_ПИР',
    9: 'СтоимостьКЧ_СМР',
    10: 'СтоимостьКЧ_ТМЦ',
    11: 'СтоимостьТО',
    12: 'СтоимостьВДГО',
    13: 'СтоимостьМонтажБезГаза',
    14: 'ОплаченосНДС',
    15: 'ОплаченобезНДС',
    16: 'ДатаАванса',
    17: 'AGR_REQ_GUID'
}

In [10]:
hist_agr = hist_agr.rename(columns=columnnames)
hist_agr.head(2)

,AGR_GUID,Статус,Номер,Дата,ДатаНачалаДействия,ДатаОкончанияДействия,ДатаПодписанияДоговораЗаявителем,СтоимостьДоговора,СтоимостьКЧ_ПИР,СтоимостьКЧ_СМР,СтоимостьКЧ_ТМЦ,СтоимостьТО,СтоимостьВДГО,СтоимостьМонтажБезГаза,ОплаченосНДС,ОплаченобезНДС,ДатаАванса,AGR_REQ_GUID,18
0,00dd53ee-7ec5-11ec-8981-0050569c399d,Действует,08/-Д13358-21,2021-10-08 00:00:00.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,00dd53ef-7ec5-11ec-8981-0050569c399d,2022-02-13
1,00dd53f2-7ec5-11ec-8981-0050569c399d,Действует,08/-Д13359-21,2021-10-08 00:00:00.000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,00dd53f3-7ec5-11ec-8981-0050569c399d,2022-02-13

In [11]:
hist_agr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103268 entries, 0 to 103267
Data columns (total 19 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   AGR_GUID                          103268 non-null  object
 1   Статус                            103268 non-null  object
 2   Номер                             103268 non-null  object
 3   Дата                              103157 non-null  object
 4   ДатаНачалаДействия                63320 non-null   object
 5   ДатаОкончанияДействия             64125 non-null   object
 6   ДатаПодписанияДоговораЗаявителем  26761 non-null   object
 7   СтоимостьДоговора                 103268 non-null  float64
 8   СтоимостьКЧ_ПИР                   103268 non-null  float64
 9   СтоимостьКЧ_СМР                   103268 non-null  float64
 10  СтоимостьКЧ_ТМЦ                   103268 non-null  float64
 11  СтоимостьТО                       103268 non-null  float64
 12  СтоимостьВДГО                     103268 non-null  float64
 13  СтоимостьМонтажБезГаза            103268 non-null  float64
 14  ОплаченосНДС                      24131 non-null   float64
 15  ОплаченобезНДС                    24131 non-null   float64
 16  ДатаАванса                        24131 non-null   object
 17  AGR_REQ_GUID                      103268 non-null  object
 18  18                                103268 non-null  object
dtypes: float64(9), object(10)
memory usage: 15.0+ MB

In [12]:
hist_req = pd.read_csv('socgaz_hist_REQ.csv', sep = ';', header = None)
hist_req.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,398286020,34db1301-24f7-11ec-8980-0050569c399d,0,0,0600-023318,Д14732,2021-10-04 12:58:22.000,"142326, Московская обл, Чеховский р-н, Васькино д",Газификация жилого дома по адресу: Московская ...,Жилой дом,Лично,Соколова Анастасия Николаевна,Физ. лицо,92631464-665d-11ec-8980-0050569c399d,41f40aff-60df-11ec-8980-0050569c399d,2022-02-13
1,398269377,fc701360-ce18-11eb-8912-0050569c399d,0,0,0800-002955,Д0343,2021-06-15 23:33:55.000,"142530, Московская обл, Электрогорск г, 5-я Юг...","жилой дом, Московская область, г. Электрогорск...",Жилой дом,Внешняя информационная система,Тюменева Светлана Анатольевна,Физ. лицо,00000000-0000-0000-0000-000000000000,8a6209fe-68ab-11ec-8980-0050569c399d,2022-02-13

In [13]:
# На основе анализа таблицы REQ по записи 34db1301-24f7-11ec-8980-0050569c399d в отчете PowerBI определяем названия полей
columnnames = {
    0: 'SETTL_FID',
    1: 'REQ_GUID',
    2: 'IsDell',
    3: 'ДелоАннулировано',
    4: 'Номер',
    5: 'НомерДела',
    6: 'Дата',
    7: 'Адрес',
    8: 'ОбъектПрисоединения',
    9: 'Тип объекта',
    10: 'СпособПодачиЗаявления',
    11: 'Заявитель',
    12: 'Тип заявителя',
    13: 'AGR_GUID',
    14: 'AGR.AGR_GUID'
}

In [14]:
hist_req = hist_req.rename(columns=columnnames)
hist_req.head(2)

,SETTL_FID,REQ_GUID,IsDell,ДелоАннулировано,Номер,НомерДела,Дата,Адрес,ОбъектПрисоединения,Тип объекта,СпособПодачиЗаявления,Заявитель,Тип заявителя,AGR_GUID,AGR.AGR_GUID,15
0,398286020,34db1301-24f7-11ec-8980-0050569c399d,0,0,0600-023318,Д14732,2021-10-04 12:58:22.000,"142326, Московская обл, Чеховский р-н, Васькино д",Газификация жилого дома по адресу: Московская ...,Жилой дом,Лично,Соколова Анастасия Николаевна,Физ. лицо,92631464-665d-11ec-8980-0050569c399d,41f40aff-60df-11ec-8980-0050569c399d,2022-02-13
1,398269377,fc701360-ce18-11eb-8912-0050569c399d,0,0,0800-002955,Д0343,2021-06-15 23:33:55.000,"142530, Московская обл, Электрогорск г, 5-я Юг...","жилой дом, Московская область, г. Электрогорск...",Жилой дом,Внешняя информационная система,Тюменева Светлана Анатольевна,Физ. лицо,00000000-0000-0000-0000-000000000000,8a6209fe-68ab-11ec-8980-0050569c399d,2022-02-13

In [15]:
hist_req['REQ_GUID'].nunique()

89123

In [16]:
hist_req.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267275 entries, 0 to 267274
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   SETTL_FID              267275 non-null  int64
 1   REQ_GUID               267275 non-null  object
 2   IsDell                 267275 non-null  int64
 3   ДелоАннулировано       267275 non-null  int64
 4   Номер                  267275 non-null  object
 5   НомерДела              265640 non-null  object
 6   Дата                   267269 non-null  object
 7   Адрес                  267218 non-null  object
 8   ОбъектПрисоединения    267275 non-null  object
 9   Тип объекта            265109 non-null  object
 10  СпособПодачиЗаявления  267263 non-null  object
 11  Заявитель              267104 non-null  object
 12  Тип заявителя          266300 non-null  object
 13  AGR_GUID               267275 non-null  object
 14  AGR.AGR_GUID           267275 non-null  object
 15  15                     267275 non-null  object
dtypes: int64(3), object(13)
memory usage: 32.6+ MB

Формат выходной таблицы:<br>
DT – дата , <br>
SETTL_FID из [SocGaz_hist_REQ], <br>
REQ_GUID из [SocGaz_hist_REQ],<br>
 ERROR_TYPE – текст из списка [‘Заявка просрочена’,’Работа есть/договора нет’,’Есть пуск нет СМР’,'Договор просрочен' ], <br>
ERROR_COUNT – 1

# Реализация фильтров
## Заявка просрочена
Из таблицы REQ

f.ЗаявкаПросрочена = if([Заявок просрочено]=1,"Да","Нет")

Заявок просрочено = if(ISBLANK([AGR.AGR_GUID])&&[Заявок анулировано]=0&&(DATEDIFF([Дата].[Date],now(),DAY)-30)>0,1,0)

[Заявок анулировано]=0 когда ДелоАннулировано=0

In [17]:
reqdate_err = hist_req[['Дата','SETTL_FID','REQ_GUID','ДелоАннулировано','AGR.AGR_GUID']]
reqdate_err['Дата'] = pd.to_datetime(reqdate_err['Дата'])
reqdate_err['Дней от даты'] = (pd.to_datetime('today').normalize()-reqdate_err['Дата'] ).dt.days

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\2572077057.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reqdate_err['Дата'] = pd.to_datetime(reqdate_err['Дата'])
C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\2572077057.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reqdate_err['Дней от даты'] = (pd.to_datetime('today').normalize()-reqdate_err['Дата'] ).dt.days

In [18]:
reqdate_err.info()
# Есть записи с пустым полем дата

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267275 entries, 0 to 267274
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Дата              267269 non-null  datetime64[ns]
 1   SETTL_FID         267275 non-null  int64
 2   REQ_GUID          267275 non-null  object
 3   ДелоАннулировано  267275 non-null  int64
 4   AGR.AGR_GUID      267275 non-null  object
 5   Дней от даты      267269 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 12.2+ MB

In [19]:
reqdate_err.head(2)

,Дата,SETTL_FID,REQ_GUID,ДелоАннулировано,AGR.AGR_GUID,Дней от даты
0,2021-10-04 12:58:22,398286020,34db1301-24f7-11ec-8980-0050569c399d,0,41f40aff-60df-11ec-8980-0050569c399d,344.0
1,2021-06-15 23:33:55,398269377,fc701360-ce18-11eb-8912-0050569c399d,0,8a6209fe-68ab-11ec-8980-0050569c399d,455.0

In [20]:
# Выделение записей по условиям для просроченной заявки. Вместо поля 'Заявок анулировано' использавано совпадающее поле 'ДелоАннулировано'
reqdate_err_list = reqdate_err[['Дата','SETTL_FID','REQ_GUID']].loc[(reqdate_err['Дата'].notna()) &
                              (reqdate_err['AGR.AGR_GUID'].isna()) & 
                              (reqdate_err['ДелоАннулировано']==0) &
                              (reqdate_err['Дней от даты']>30)
                              ]
reqdate_err_list['Error_type'] = 'Заявка просрочена'
reqdate_err_list['Error_count'] = 1

In [21]:
reqdate_err_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Дата         0 non-null      datetime64[ns]
 1   SETTL_FID    0 non-null      int64
 2   REQ_GUID     0 non-null      object
 3   Error_type   0 non-null      object
 4   Error_count  0 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 0.0+ bytes

## Работа есть/договора нет

Из таблицы REQ

f.ЕстьРаботыНетДоговора = if([и.ЕстьПускИсполненоДоГраниц-НетДоговора]=1,"Да","Нет")

и.ЕстьПускИсполненоДоГраниц-НетДоговора = if(([Исполнено до границ]=1||[Пуск]=1)&&ISBLANK([AGR.AGR_GUID]),1,0)

Исполнено до границ = if(not ISBLANK([Дата исполнения пуска].[Date])&&[Заявок анулировано]=0, 1,
                            if(ISBLANK([Дата исполнения до границ].[Date])||[Заявок анулировано]=1,0,1))

Дата исполнения пуска = RELATED(ADDR[ДатаПускаГаза].[Date])

Дата исполнения до границ = RELATED(ADDR[ДатаСтроительстваГазопроводВвода].[Date])

Пуск = if(ISBLANK([Дата исполнения пуска].[Date])||[Заявок анулировано]=1,0,1)

In [22]:
# Объединение слева таблиц REQ и ADR по полю 'REQ_GUID'
req_adr = pd.merge(hist_req, hist_addr, on = 'REQ_GUID', how = 'left')

In [23]:
req_adr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518213 entries, 0 to 518212
Data columns (total 29 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   SETTL_FID_x                       518213 non-null  int64
 1   REQ_GUID                          518213 non-null  object
 2   IsDell                            518213 non-null  int64
 3   ДелоАннулировано                  518213 non-null  int64
 4   Номер                             518213 non-null  object
 5   НомерДела                         516506 non-null  object
 6   Дата                              518195 non-null  object
 7   Адрес_x                           518156 non-null  object
 8   ОбъектПрисоединения               518213 non-null  object
 9   Тип объекта                       513653 non-null  object
 10  СпособПодачиЗаявления             518201 non-null  object
 11  Заявитель                         517970 non-null  object
 12  Тип заявителя                     517166 non-null  object
 13  AGR_GUID                          518213 non-null  object
 14  AGR.AGR_GUID                      518213 non-null  object
 15  15                                518213 non-null  object
 16  SETTL_FID_y                       375849 non-null  float64
 17  ADDR_GUID                         375849 non-null  object
 18  Адрес_y                           373797 non-null  object
 19  КадастровыйНомерОбъектаКС         159321 non-null  object
 20  АдресОбъектаКС                    206961 non-null  object
 21  ТипОбъектаКС                      193509 non-null  object
 22  КадастровыйНомерЗУ                341028 non-null  object
 23  АдресЗУ                           300582 non-null  object
 24  ДатаСтроительстваГазопроводВвода  127530 non-null  object
 25  ДатаВыполненияПИР_КЧ              15288 non-null   object
 26  ДатаВыполненияСМР_КЧ              15993 non-null   object
 27  ДатаПускаГаза                     23904 non-null   object
 28  13                                375849 non-null  object
dtypes: float64(1), int64(3), object(25)
memory usage: 118.6+ MB

In [24]:
# Выбор подмножества столбцов для анализа
req_adr = req_adr[['Дата','SETTL_FID_x','REQ_GUID','ДелоАннулировано','ДатаПускаГаза','ДатаСтроительстваГазопроводВвода','AGR.AGR_GUID']]

In [25]:
req_adr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518213 entries, 0 to 518212
Data columns (total 7 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Дата                              518195 non-null  object
 1   SETTL_FID_x                       518213 non-null  int64
 2   REQ_GUID                          518213 non-null  object
 3   ДелоАннулировано                  518213 non-null  int64
 4   ДатаПускаГаза                     23904 non-null   object
 5   ДатаСтроительстваГазопроводВвода  127530 non-null  object
 6   AGR.AGR_GUID                      518213 non-null  object
dtypes: int64(2), object(5)
memory usage: 31.6+ MB

In [26]:
# Реализация условия 'Пуск'
req_adr['Пуск'] = 1
index = req_adr.loc[(req_adr['ДелоАннулировано']==1)|(req_adr['ДатаПускаГаза'].isna())].index
req_adr['Пуск'].loc[index] = 0

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\2309099773.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['Пуск'].loc[index] = 0

In [27]:
# Реализация условия 'Исполнено до границ'.

req_adr['Исполнено до границ'] = 0
req_adr['Исполнено до границ'].loc[(req_adr['ДатаПускаГаза'].notna()) & (req_adr['ДелоАннулировано']==0)] = 1
req_adr['Исполнено до границ'].loc[(req_adr['ДатаСтроительстваГазопроводВвода'].isna()) | (req_adr['ДелоАннулировано']==1)] = 0
req_adr['Исполнено до границ'].loc[~((req_adr['ДатаСтроительстваГазопроводВвода'].isna()) | (req_adr['ДелоАннулировано']==1))] = 1

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3796309679.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['Исполнено до границ'].loc[(req_adr['ДатаПускаГаза'].notna()) & (req_adr['ДелоАннулировано']==0)] = 1
C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3796309679.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['Исполнено до границ'].loc[(req_adr['ДатаСтроительстваГазопроводВвода'].isna()) | (req_adr['ДелоАннулировано']==1)] = 0
C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3796309679.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['Исполнено до границ'].loc[~((req_adr['ДатаСтроительстваГазопроводВвода'].isna()) | (req_adr['ДелоАннулировано']==1))] = 1

In [28]:
# Реализация условия 'ЕстьПускИсполненоДоГраниц-НетДоговора'.

req_adr['ЕстьПускИсполненоДоГраниц-НетДоговора'] = 0
index = req_adr.loc[((req_adr['Исполнено до границ']==1)|(req_adr['Пуск']==1))&(req_adr['AGR.AGR_GUID'].isna())].index
req_adr['ЕстьПускИсполненоДоГраниц-НетДоговора'].loc[index] = 1

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3129136042.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['ЕстьПускИсполненоДоГраниц-НетДоговора'].loc[index] = 1

In [29]:
req_adr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518213 entries, 0 to 518212
Data columns (total 10 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Дата                                   518195 non-null  object
 1   SETTL_FID_x                            518213 non-null  int64
 2   REQ_GUID                               518213 non-null  object
 3   ДелоАннулировано                       518213 non-null  int64
 4   ДатаПускаГаза                          23904 non-null   object
 5   ДатаСтроительстваГазопроводВвода       127530 non-null  object
 6   AGR.AGR_GUID                           518213 non-null  object
 7   Пуск                                   518213 non-null  int64
 8   Исполнено до границ                    518213 non-null  int64
 9   ЕстьПускИсполненоДоГраниц-НетДоговора  518213 non-null  int64
dtypes: int64(5), object(5)
memory usage: 59.6+ MB

In [30]:
# Формирование итогового списка для фильтра ’Работа есть/договора нет’

req_adr_err_list = req_adr[['Дата', 'SETTL_FID_x','REQ_GUID']].loc[req_adr['ЕстьПускИсполненоДоГраниц-НетДоговора']==1]
req_adr_err_list['Error_type'] = 'Работа есть/договора нет'
req_adr_err_list['Error_count'] = 1

In [31]:
req_adr_err_list.rename(columns={'SETTL_FID_x': 'SETTL_FID'},inplace=True)
req_adr_err_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Дата         0 non-null      object
 1   SETTL_FID    0 non-null      int64
 2   REQ_GUID     0 non-null      object
 3   Error_type   0 non-null      object
 4   Error_count  0 non-null      int64
dtypes: int64(2), object(3)
memory usage: 0.0+ bytes

In [32]:
# Удаление из итогового списка записей с пустой датой
req_adr_err_list = req_adr_err_list.loc[req_adr_err_list['Дата'].notna()]

In [33]:
req_adr_err_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Дата         0 non-null      object
 1   SETTL_FID    0 non-null      int64
 2   REQ_GUID     0 non-null      object
 3   Error_type   0 non-null      object
 4   Error_count  0 non-null      int64
dtypes: int64(2), object(3)
memory usage: 0.0+ bytes

## Есть пуск нет СМР

Из таблицы REQ

f.ЕстьПускНетСМР = if([и.ЕстьПускНетСМР]=0,"Нет","Да")

и.ЕстьПускНетСМР = if([Пуск]=1&&ISBLANK([Дата исполнения СМР]),1,0)

Пуск = if(ISBLANK([Дата исполнения пуска].[Date])||[Заявок анулировано]=1,0,1)

Дата исполнения СМР = RELATED(ADDR[ДатаВыполненияСМР_КЧ].[Date])

Дата исполнения пуска = RELATED(ADDR[ДатаПускаГаза].[Date])

In [34]:
# Объединение слева таблиц REQ и ADR по полю 'REQ_GUID'
req_adr = pd.merge(hist_req, hist_addr, on = 'REQ_GUID', how = 'left')
req_adr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518213 entries, 0 to 518212
Data columns (total 29 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   SETTL_FID_x                       518213 non-null  int64
 1   REQ_GUID                          518213 non-null  object
 2   IsDell                            518213 non-null  int64
 3   ДелоАннулировано                  518213 non-null  int64
 4   Номер                             518213 non-null  object
 5   НомерДела                         516506 non-null  object
 6   Дата                              518195 non-null  object
 7   Адрес_x                           518156 non-null  object
 8   ОбъектПрисоединения               518213 non-null  object
 9   Тип объекта                       513653 non-null  object
 10  СпособПодачиЗаявления             518201 non-null  object
 11  Заявитель                         517970 non-null  object
 12  Тип заявителя                     517166 non-null  object
 13  AGR_GUID                          518213 non-null  object
 14  AGR.AGR_GUID                      518213 non-null  object
 15  15                                518213 non-null  object
 16  SETTL_FID_y                       375849 non-null  float64
 17  ADDR_GUID                         375849 non-null  object
 18  Адрес_y                           373797 non-null  object
 19  КадастровыйНомерОбъектаКС         159321 non-null  object
 20  АдресОбъектаКС                    206961 non-null  object
 21  ТипОбъектаКС                      193509 non-null  object
 22  КадастровыйНомерЗУ                341028 non-null  object
 23  АдресЗУ                           300582 non-null  object
 24  ДатаСтроительстваГазопроводВвода  127530 non-null  object
 25  ДатаВыполненияПИР_КЧ              15288 non-null   object
 26  ДатаВыполненияСМР_КЧ              15993 non-null   object
 27  ДатаПускаГаза                     23904 non-null   object
 28  13                                375849 non-null  object
dtypes: float64(1), int64(3), object(25)
memory usage: 118.6+ MB

In [35]:
# Выбор подмножества столбцов для анализа
req_adr = req_adr[['Дата', 'SETTL_FID_x', 'REQ_GUID', 'ДатаВыполненияСМР_КЧ', 'ДелоАннулировано', 'ДатаПускаГаза']]

In [36]:
# Реализация условия 'Пуск'
req_adr['Пуск'] = 1
index = req_adr.loc[(req_adr['ДелоАннулировано']==1)|(req_adr['ДатаПускаГаза'].isna())].index
req_adr['Пуск'].loc[index] = 0

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\2309099773.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['Пуск'].loc[index] = 0

In [37]:
# Реализация условия 'ЕстьПускНетСМР'
req_adr['ЕстьПускНетСМР'] = 0
index = req_adr.loc[(req_adr['Пуск']==1)&(req_adr['ДатаВыполненияСМР_КЧ'].isna())].index
req_adr['ЕстьПускНетСМР'].loc[index] = 1

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\2384390122.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_adr['ЕстьПускНетСМР'].loc[index] = 1

In [38]:
# Формирование итогового списка для фильтра ’Есть пуск нет СМР’
req_adr_smr_list = req_adr[['Дата', 'SETTL_FID_x','REQ_GUID']].loc[req_adr['ЕстьПускНетСМР']==1]
req_adr_smr_list['Error_type'] = 'Есть пуск нет СМР'
req_adr_smr_list['Error_count'] = 1

In [39]:
req_adr_smr_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13779 entries, 69 to 518131
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Дата         13779 non-null  object
 1   SETTL_FID_x  13779 non-null  int64
 2   REQ_GUID     13779 non-null  object
 3   Error_type   13779 non-null  object
 4   Error_count  13779 non-null  int64
dtypes: int64(2), object(3)
memory usage: 645.9+ KB

In [40]:
req_adr_smr_list.rename(columns={'SETTL_FID_x':'SETTL_FID'}, inplace=True)
req_adr_smr_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13779 entries, 69 to 518131
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Дата         13779 non-null  object
 1   SETTL_FID    13779 non-null  int64
 2   REQ_GUID     13779 non-null  object
 3   Error_type   13779 non-null  object
 4   Error_count  13779 non-null  int64
dtypes: int64(2), object(3)
memory usage: 645.9+ KB

## Договор просрочен

Из таблицы REQ

f.ДоговорПросрочен = if([Договоров просрочено]=1,"Да","Нет")

Договоров просрочено = 
    var pd = if(ISBLANK([AGR.ДатаОкончанияДействия]),NOW(),[AGR.ДатаОкончанияДействия])
    var st = if(isblank([AGR.Дата подписания/аванса]),0,if([AGR.Тип]="ТП0",
                    if(pd<now()&&ISBLANK([Дата исполнения до границ]),1,0),
                            if([AGR.Тип]="КД",if(pd<now()&&ISBLANK([Дата исполнения пуска]),1,0))))
    return st

Дата исполнения до границ = RELATED(ADDR[ДатаСтроительстваГазопроводВвода].[Date])

Дата исполнения пуска = RELATED(ADDR[ДатаПускаГаза].[Date])


= Table.AddColumn(#"Измененный тип", "Тип", each if ([СтоимостьКЧ_ПИР]+[СтоимостьКЧ_СМР]+[СтоимостьКЧ_ТМЦ]+[СтоимостьТО]+[СтоимостьВДГО]+[СтоимостьМонтажБезГаза])>0 then "КД" else "ТП0")

= Table.AddColumn(#"Тип договора", "Дата подписания/аванса", each if [ДатаПодписанияДоговораЗаявителем]=null then [ДатаАванса] else [ДатаПодписанияДоговораЗаявителем])

In [41]:
# Объединение слева таблиц REQ, AGR по полю 'AGR_GUID', потом слева с ADR по полю 'REQ_GUID'
req_agr = pd.merge(hist_req, hist_agr, on = 'AGR_GUID', how = 'left')
req_agr_adr = pd.merge(req_agr, hist_addr, on = 'REQ_GUID', how = 'left')
req_agr_adr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1002512 entries, 0 to 1002511
Data columns (total 47 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   SETTL_FID_x                       1002512 non-null  int64
 1   REQ_GUID                          1002512 non-null  object
 2   IsDell                            1002512 non-null  int64
 3   ДелоАннулировано                  1002512 non-null  int64
 4   Номер_x                           1002512 non-null  object
 5   НомерДела                         1000775 non-null  object
 6   Дата_x                            1002458 non-null  object
 7   Адрес_x                           1002455 non-null  object
 8   ОбъектПрисоединения               1002512 non-null  object
 9   Тип объекта                       995588 non-null   object
 10  СпособПодачиЗаявления             1002500 non-null  object
 11  Заявитель                         1002245 non-null  object
 12  Тип заявителя                     999833 non-null   object
 13  AGR_GUID                          1002512 non-null  object
 14  AGR.AGR_GUID                      1002512 non-null  object
 15  15                                1002512 non-null  object
 16  Статус                            727251 non-null   object
 17  Номер_y                           727251 non-null   object
 18  Дата_y                            726522 non-null   object
 19  ДатаНачалаДействия                472042 non-null   object
 20  ДатаОкончанияДействия             478978 non-null   object
 21  ДатаПодписанияДоговораЗаявителем  222669 non-null   object
 22  СтоимостьДоговора                 727251 non-null   float64
 23  СтоимостьКЧ_ПИР                   727251 non-null   float64
 24  СтоимостьКЧ_СМР                   727251 non-null   float64
 25  СтоимостьКЧ_ТМЦ                   727251 non-null   float64
 26  СтоимостьТО                       727251 non-null   float64
 27  СтоимостьВДГО                     727251 non-null   float64
 28  СтоимостьМонтажБезГаза            727251 non-null   float64
 29  ОплаченосНДС                      200652 non-null   float64
 30  ОплаченобезНДС                    200652 non-null   float64
 31  ДатаАванса                        200652 non-null   object
 32  AGR_REQ_GUID                      727251 non-null   object
 33  18                                727251 non-null   object
 34  SETTL_FID_y                       804024 non-null   float64
 35  ADDR_GUID                         804024 non-null   object
 36  Адрес_y                           800487 non-null   object
 37  КадастровыйНомерОбъектаКС         350718 non-null   object
 38  АдресОбъектаКС                    442215 non-null   object
 39  ТипОбъектаКС                      416763 non-null   object
 40  КадастровыйНомерЗУ                717165 non-null   object
 41  АдресЗУ                           621945 non-null   object
 42  ДатаСтроительстваГазопроводВвода  360360 non-null   object
 43  ДатаВыполненияПИР_КЧ              45066 non-null    object
 44  ДатаВыполненияСМР_КЧ              47199 non-null    object
 45  ДатаПускаГаза                     70803 non-null    object
 46  13                                804024 non-null   object
dtypes: float64(10), int64(3), object(34)
memory usage: 367.1+ MB

In [42]:
# Для реализации фильтра нужны поля "ARG.Тип" и "AGR.Дата подписания/аванса", которых нет выборке
# Вместо поля "AGR.Дата подписания/аванса" взято совпадающее поле 'ДатаПодписанияДоговораЗаявителем'

req_agr_adr = req_agr_adr[['Дата_x','SETTL_FID_x',
                            'REQ_GUID',
                            'ДатаПускаГаза',
                            'ДатаСтроительстваГазопроводВвода',
                            'ДатаОкончанияДействия', 
                            'ДатаПодписанияДоговораЗаявителем', 
                            'СтоимостьКЧ_ПИР', 
                            'СтоимостьКЧ_СМР', 
                            'СтоимостьКЧ_ТМЦ', 
                            'СтоимостьТО', 
                            'СтоимостьВДГО', 
                            'СтоимостьМонтажБезГаза', 
                            'ДатаАванса']]

In [43]:
# Преобразование дат к типу Datetime
req_agr_adr['Дата_x'] = pd.to_datetime(req_agr_adr['Дата_x'])
req_agr_adr['ДатаПускаГаза'] = pd.to_datetime(req_agr_adr['ДатаПускаГаза'])
req_agr_adr['ДатаСтроительстваГазопроводВвода'] = pd.to_datetime(req_agr_adr['ДатаСтроительстваГазопроводВвода'])
req_agr_adr['ДатаОкончанияДействия'] = pd.to_datetime(req_agr_adr['ДатаОкончанияДействия'])
req_agr_adr['ДатаПодписанияДоговораЗаявителем'] = pd.to_datetime(req_agr_adr['ДатаПодписанияДоговораЗаявителем'])
req_agr_adr['ДатаАванса'] = pd.to_datetime(req_agr_adr['ДатаАванса'])

In [44]:
req_agr_adr['Дата подписания/аванса'] = req_agr_adr['ДатаПодписанияДоговораЗаявителем']
index = req_agr_adr['Дата подписания/аванса'].loc[req_agr_adr['Дата подписания/аванса'].isna()].index
req_agr_adr['Дата подписания/аванса'].loc[index] = req_agr_adr['ДатаАванса'].loc[index]

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\40067825.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_agr_adr['Дата подписания/аванса'].loc[index] = req_agr_adr['ДатаАванса'].loc[index]

In [45]:
# Создание поля Тип.

req_agr_adr['AGR.Тип'] = req_agr_adr['СтоимостьКЧ_ПИР']+req_agr_adr['СтоимостьКЧ_СМР']+req_agr_adr['СтоимостьКЧ_ТМЦ']+req_agr_adr['СтоимостьТО']+req_agr_adr['СтоимостьВДГО']+req_agr_adr['СтоимостьМонтажБезГаза']
req_agr_adr['Тип'] = 'ТП0'
req_agr_adr['Тип'].loc[req_agr_adr['AGR.Тип']>0] = 'КД'
req_agr_adr['Тип'].value_counts()

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\840164578.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_agr_adr['Тип'].loc[req_agr_adr['AGR.Тип']>0] = 'КД'

ТП0    627890
КД     374622
Name: Тип, dtype: int64

In [46]:
# Функция для посчета просроченных договоров втупую. Она медленная, но понятная. Ориентировался на ее результаты, 
# когда реализовывал 4-х этажное условие средставами pandas

def get_req_err(i):
    fpd = 0
    DateNow = pd.to_datetime('today').normalize()
    DateFinAct = DateNow if pd.isna(req_agr_adr['ДатаОкончанияДействия'].iloc[i]) else req_agr_adr['ДатаОкончанияДействия'].iloc[i]
    DateAvans = req_agr_adr['Дата подписания/аванса'].iloc[i]
    DateGazIn = req_agr_adr['ДатаСтроительстваГазопроводВвода'].iloc[i]
    DatePusk = req_agr_adr['ДатаПускаГаза'].iloc[i]
    Type = req_agr_adr['Тип'].iloc[i]
    if pd.isna(DateAvans): fpd =0
    elif Type == 'ТП0':
        if (DateFinAct < DateNow) & (pd.isna(DateGazIn)): fpd = 1
        else: fpd =0
    elif Type == 'КД':
        if (DateFinAct < DateNow) & (pd.isna(DatePusk)): fpd = 1
        else: fpd = 0
    return fpd

In [47]:
req_agr_adr['st_slow'] = req_agr_adr.index
req_agr_adr['st_slow'] = req_agr_adr['st_slow'].apply(get_req_err)
req_agr_adr['st_slow'].value_counts()

0    843875
1    158637
Name: st_slow, dtype: int64

In [48]:
# Рассчет просроченных договоров функциями pandas
DateNow = pd.to_datetime('today').normalize()

req_agr_adr['st_fast'] = 0
req_agr_adr['DateFinAct'] = req_agr_adr['ДатаОкончанияДействия']
req_agr_adr['DateFinAct'].apply(lambda x: DateNow if pd.isna(x) else x)

req_agr_adr['st_fast'].loc[(req_agr_adr['Дата подписания/аванса'].notna())&(req_agr_adr['Тип']=='ТП0')&(req_agr_adr['DateFinAct'] < DateNow) & (req_agr_adr['ДатаСтроительстваГазопроводВвода'].isna())] = 1
req_agr_adr['st_fast'].loc[(req_agr_adr['Дата подписания/аванса'].notna())&(req_agr_adr['Тип']=='КД')&(req_agr_adr['DateFinAct'] < DateNow) & (req_agr_adr['ДатаПускаГаза'].isna())] = 1

C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3102952556.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_agr_adr['st_fast'].loc[(req_agr_adr['Дата подписания/аванса'].notna())&(req_agr_adr['Тип']=='ТП0')&(req_agr_adr['DateFinAct'] < DateNow) & (req_agr_adr['ДатаСтроительстваГазопроводВвода'].isna())] = 1
C:\Users\kamik\AppData\Local\Temp\ipykernel_13488\3102952556.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  req_agr_adr['st_fast'].loc[(req_agr_adr['Дата подписания/аванса'].notna())&(req_agr_adr['Тип']=='КД')&(req_agr_adr['DateFinAct'] < DateNow) & (req_agr_adr['ДатаПускаГаза'].isna())] = 1

In [49]:
req_agr_adr['st_fast'].value_counts()

0    843875
1    158637
Name: st_fast, dtype: int64

In [50]:
# Формирование итогового списка для фильтра 'Договор просрочен' 
req_agr_adr_dog_list = req_agr_adr[['Дата_x','SETTL_FID_x','REQ_GUID']].loc[req_agr_adr['st_fast']==1]
req_agr_adr_dog_list['Error_type'] = 'Договор просрочен'
req_agr_adr_dog_list['Error_count'] = 1
req_agr_adr_dog_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158637 entries, 12 to 1002489
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Дата_x       158637 non-null  datetime64[ns]
 1   SETTL_FID_x  158637 non-null  int64
 2   REQ_GUID     158637 non-null  object
 3   Error_type   158637 non-null  object
 4   Error_count  158637 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 7.3+ MB

In [51]:
req_agr_adr_dog_list.rename(columns={'Дата_x':'Дата', 'SETTL_FID_x': 'SETTL_FID'},inplace=True)

In [52]:
req_agr_adr_dog_list.drop_duplicates()
req_agr_adr_dog_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158637 entries, 12 to 1002489
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Дата         158637 non-null  datetime64[ns]
 1   SETTL_FID    158637 non-null  int64
 2   REQ_GUID     158637 non-null  object
 3   Error_type   158637 non-null  object
 4   Error_count  158637 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 7.3+ MB

# Объединение результатов

In [53]:

result_tab = [reqdate_err_list, req_adr_err_list, req_adr_smr_list, req_agr_adr_dog_list]
result = pd.concat(result_tab, ignore_index=True)
result['Error_type'].value_counts()

Договор просрочен    158637
Есть пуск нет СМР     13779
Name: Error_type, dtype: int64

In [54]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172416 entries, 0 to 172415
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Дата         172416 non-null  object
 1   SETTL_FID    172416 non-null  int64
 2   REQ_GUID     172416 non-null  object
 3   Error_type   172416 non-null  object
 4   Error_count  172416 non-null  int64
dtypes: int64(2), object(3)
memory usage: 6.6+ MB

In [55]:
result['Дата'] = pd.to_datetime(result['Дата']).dt.strftime('%Y.%m.%d')

In [56]:
result.to_csv('Socgaz_error_dynamic.csv', encoding ='cp1251', index=False, sep = ';')